//const { Graph } = require('./graph.js')
const Graph = require('./graph.js')
const UItable = require('./UItables.js')
// global.box2d = require('box2dweb-commonjs')
const circle = require('./circle.js')
require('handsontable/dist/handsontable.full.css')
require('./sketch.js')
let table, graph
graph = Graph.random(8, 0.5)
// console.log(graph)
table = new UItable('AdjTable', graph.mat)
document.getElementById('buttonCreateAdjTable').onclick = () => table.createTable()
document.getElementById('buttonDeleteAdjTable').onclick = () => table.hideTable()

let Box2D = require('box2dweb')
console.log(Box2D)
let gravity = new Box2D.Common.Math.b2Vec2(0,-10)
console.log(gravity)

//TODO: find a way to send world to p5 draw()
global.world = new Box2D.Dynamics.b2World(gravity)
console.log(world)
let worldElement = require('./worldElement.js')
console.log(worldElement)
let elements = []
elements.push(new circle(world, [1,1], Box2D.Collision.Shapes.b2CircleShape))
elements.push(new circle(world, [50,1]))
elements.push(new circle(world, [-100,1]))
console.log(world)